language: r
cache: packages
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat","ggplot2","knitr","rmarkdown"));devtools::install_deps("Lab04R")'
script:
  - Rscript -e 'devtools::check("Lab04R")'
