language: r
cache: packages
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat","knitr","rmarkdown","parallel"));devtools::install_github("hadley/lineprof");devtools::install_deps("Lab06R")'
script:
  - Rscript -e 'devtools::check("Lab06R")'
